### ISSUE TITLE
This Serverless Function has crashed.

### ISSUE THREAD

**Issue by 1998code** [anuraghazra/github-readme-stats#2047]
<img width="486" alt="CleanShot 2022-09-24 at 18 15 34@2x" src="https://user-images.githubusercontent.com/54872601/192092623-654e3099-2755-4d98-ae0f-2208d8577e1e.png">

**Comment by schmittsfn** [comment]
Here the error logs:
```
[GET] /api/pin/?username=schmittsfn&repo=STSRotateAround&theme=dark&show_owner=false
12:28:00:91
RequestId: dc88f527-1cb0-476d-8c17-fbcdbf2ea59a Error: Runtime exited with error: exit status 1
Runtime.ExitError
2022-09-24T10:28:00.985Z	undefined	ERROR	Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/src/common/utils' imported from /var/task/api/pin.js
    at new NodeError (node:internal/errors:372:5)
    at finalizeResolution (node:internal/modules/esm/resolve:437:11)
    at moduleResolve (node:internal/modules/esm/resolve:1009:10)
    at defaultResolve (node:internal/modules/esm/resolve:1218:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
RequestId: caa2e2b4-728e-49f9-b8d7-7311587cf6ac Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by schmittsfn** [comment]
Caused by this commit: https://github.com/anuraghazra/github-readme-stats/commit/107f7ca52c3431bf989e7c3624ad130e98cb4f5a

**Comment by rickstaa** [comment]
@schmittsfn Thanks for letting me know. I think it is indeed caused by https://github.com/anuraghazra/github-readme-stats/commit/107f7ca52c3431bf989e7c3624ad130e98cb4f5a. I will spend some minutes debugging it and otherwise revert #1995.
